#!/bin/bash

puppet resource package apache2 ensure=installed 
puppet resource package git ensure=installed
puppet resource service apache2 ensure=running enable=true

echo "Clean work directory" 

puppet resource file /tmp/work ensure=directory
puppet resource file /tmp/work/2124516b ensure=absent force=true
puppet resource file /tmp/work/2124516b ensure=directory

git clone https://github.com/5191-Rick/app-2124516b-repo.git /tmp/work/2124516b

puppet resource file /var/www/html/index.html ensure=file source=/tmp/work/2124516b/new_2124516b_index.html
